### ISSUE TITLE
Plugin Go2NextFeature3 : Erreur avec QGIS 3.26.2

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/ocs2d#32]
L’extension provoque l’erreur python suivante :
 
```
2023-03-01T11:01:24     WARNING    Traceback (most recent call last):
              File "C:\Users/f.perrin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Go2NextFeature3\go2nextfeature_dockwidget.py", line 431, in cbo_layer_layerchanged
              self.cbo_attrib_activated()
              File "C:\Users/f.perrin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Go2NextFeature3\go2nextfeature_dockwidget.py", line 299, in cbo_attrib_activated
              feats_d[feat] = feat.attribute(self.cbo_attribute.currentField())
             TypeError: unhashable type: 'QgsFeature'
```

 Solution de contournement trouvée : 
- Activer les extensions expérimentales
- Installer **Go2NextFeaturePlus**

Beaucoup plus d'options ou de menu, se concentrer sur le champ à parcourir et le mode (pan).

**Comment by Doctor-Who** [comment]
Issue déjà référencée sur le dépôt du code du plugin : https://gitlab.com/tabacco_editrice/go2nextfeature/-/issues/15

**Comment by Doctor-Who** [comment]
Pas de bug observé sur la nouvelle LTR 3.28 (Firenze)
Utilisation d'une LTR conseillée.
